### PR TITLE
Add UI element that shows when something is loading

### LINKED ISSUE #75: No loading info displayed
When a user clicks on the map, generally something is loaded, but most of the time the user is not informed about this and tempted to click elsewhere before loading is done and left to think the app is broken. Create some sort of loading info when:

- [x] weather data points are loading
- [x] weather popup with chart is loading
- [x] power plants are loading
- [x] feedin-series are loading

### PR DESCRIPTION
**Pull request by jh-RLI**
closes #75

### CODE REVIEW

**Comment by jh-RLI** [comment]
Currently a powerplant popup will close instandly after it opened seems like ajax.done() does this.

Edit: Seems like this have nothing to do with the spinner the problem occured somewhere else? @Bachibouzouk  @christian-rli

**Comment by jh-RLI** [comment]
#75

**Comment by jh-RLI** [comment]
Okay, the popup just closes immediately when working on a very small display (dev tools where active). So actually it works now.

**Review by Bachibouzouk — APPROVED** [review]
Nice addon! :)

**Comment by christian-rli** [comment]
Nice Addon, indeed!

**Pull request merged**
