### PR TITLE
Fire a click on the marker to open the popup in feedinlib

### LINKED ISSUE #91: Feedinlib-panel does not open the popup automatically
Once the user clicked on the map, they need to click again on the popup to display the data.

### PR DESCRIPTION
**Pull request by Bachibouzouk**
This PR is replaced by #100

### CODE REVIEW

**Comment by christian-rli** [comment]
This branch ~~fails~~ does not fail anymore (my bad), loading powerplants ~~seems to have stopped~~ works as well (more fiddling with my local settings). One can still click on on the states, because our two geojsons don't quite overlap. I guess a clean solution would be to hide the more granular regions while in the powerplants tab.

**Comment by Bachibouzouk** [comment]
> This branch ~fails~ does not fail anymore (my bad), loading powerplants ~seems to have stopped~ works as well (more fiddling with my local settings). One can still click on on the states, because our two geojsons don't quite overlap. I guess a clean solution would be to hide the more granular regions while in the powerplants tab.

I worked on that, I couldn't push yet because I need to make the commits nicer, but consider it done

**Comment by Bachibouzouk** [comment]
@christian-rli , @jh-RLI : this is still not working with the power plant (just a problem of getting a non empty query), I will notify you when it is ready to be reviewed

**Comment by christian-rli** [comment]
I can confirm that everything works except power plants. Ready to review when it's done :)

**Comment by christian-rli** [comment]
PS: can you send me or push your "landkreis_map_to_region.json"

**Comment by Bachibouzouk** [comment]
Moved to #100

**Pull request closed without merging**
