### PR TITLE
Feature/timeseries

### PR DESCRIPTION
**Pull request by jh-RLI**
- Include TimeSeries Data for visualization in graph

### CODE REVIEW

**Comment by jh-RLI** [comment]
#57

**Comment by christian-rli** [comment]
The timeseries table (test as well as the final table) has the following columns: index, id, time, feedin, nut and technology. 

`feedin` is what we want to show up in a graph over `time`.
`nut` defines the region with an identifying string. Since we only have test data at the moment, we only have one `nut` region (DE804) and one `technology` (Wind). 
Eventually we would have liked to be able to click on a region and be able to show the feedin for a freely selectable timeframe and technology. 
For now it will suffice to click anywhere on the map and show the feedin of the same example region over the entire time (2016-01-02 08:30  - 2016-01-03 00:30). It might be useful to define dummy functions for the actual data set later on, but at the moment it's a nice to have. 
(For full functionality there will have eventually have to be another geojson with the nut-region-names of the database. I can take care of that)

**Comment by Bachibouzouk** [comment]
> Eventually we would have liked to be able to click on a region and be able to show the feedin for a freely selectable timeframe and technology.

@christian-rli This is easily implementable once #47 is merged

**Comment by Bachibouzouk** [comment]
@christian-rli - this one is ready to be reviewed :), now the click only affect the function specific to each panel

**Review by christian-rli — APPROVED** [review]
Good work! 
Works.

**Pull request merged**
