### PR TITLE
Wetterdaten options

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Upon change of variable the possible heights are displayed 

When the popup is open, the the query will be sent to the server to fetch new data for each change of `variable`, but not for the change of `height`. 

The change of time span is not very intuitive for the time being

### CODE REVIEW

**Comment by christian-rli** [comment]
Preset heights work for air_pressure and air_temperature. However, if there is an active popup and I change the height, the map will try to reload the popup and fail with
```
ValueError: invalid literal for int() with base 10: 'find_something_unique'
[24/Jul/2019 17:13:50] "POST /WAM_APP_FRED/WeatherPointClick.data/ HTTP/1.1" 500 18440
```
Also, none of the other variables work. Maybe we should remove them until the query works for them as well?

**Comment by Bachibouzouk** [comment]
> Preset heights work for air_pressure and air_temperature. However, if there is an active popup and I change the height, the map will try to reload the popup and fail with
> 
> ```
> ValueError: invalid literal for int() with base 10: 'find_something_unique'
> [24/Jul/2019 17:13:50] "POST /WAM_APP_FRED/WeatherPointClick.data/ HTTP/1.1" 500 18440
> ```
> 
> Also, none of the other variables work. Maybe we should remove them until the query works for them as well?

For me the other variables work.

This error is because the ID of a geojson was set by me to 'find_something_unique' so that we could identify the marker (and because I didn't have time at the time to deal with this), I will assign an int

**Comment by christian-rli** [comment]
> For me the other variables work.

Oh. You're right. Nothing else worked for me last time, but now some more variables do, albeit not all. Some don't show values (like different wind_speed_heights). I will look more into this and give you an update here.  At least none of the selections produce errors anymore. They did a minute ago, but since I'm not able to reproduce it, it was either on another branch or just a random hick-up.

**Comment by christian-rli** [comment]
✓ air_temperature
✕ windspeed -> no data for any heights
✕ subsurface_runoff_amount -> no data
✕ water evaporation amount -> no data
✓ air_temperature_2m ✓
✕ surface_normalized_downwelling_shortwave_flux_in_air -> no data
✓ surface air pressure ✓
✕ snow amount -> no data (i checked jan/feb in the alps)
✕ surface_diffuse_downwelling_shortwave_flux_in_air -> no data
✕ surface_runoff_amount -> no data
✕ precipitation_ammount -> no data
✕ wind_speed_10m -> no data
✓ surface roughness length ✓
✕ surface_direct_downwelling_shortwave_flux_in_air -> no data

**Comment by Bachibouzouk** [comment]
@christian-rli - to test the changes I pushed you might have to do `git fetch --all` followed by `git reset --hard origin/feature/wetterdaten-options` from your local version of `feature/wetterdaten-options`

**Comment by Bachibouzouk** [comment]
> ✓ air_temperature
> ✕ windspeed -> no data for any heights
> ✕ subsurface_runoff_amount -> no data
> ✕ water evaporation amount -> no data
> ✓ air_temperature_2m ✓
> ✕ surface_normalized_downwelling_shortwave_flux_in_air -> no data
> ✓ surface air pressure ✓
> ✕ snow amount -> no data (i checked jan/feb in the alps)
> ✕ surface_diffuse_downwelling_shortwave_flux_in_air -> no data
> ✕ surface_runoff_amount -> no data
> ✕ precipitation_ammount -> no data
> ✕ wind_speed_10m -> no data
> ✓ surface roughness length ✓
> ✕ surface_direct_downwelling_shortwave_flux_in_air -> no data

Maybe it is only for other years? I would not remove them, we can ask the curator of this table of the OEP for which years there is the most data.

**Comment by christian-rli** [comment]
> Maybe it is only for other years?

Maybe. I'll check. In any case i don't know if it's nice to leave them in, when they don't show anything in a realistic/normal setting.

... I checked some more years, but the ✕ variables don't show any data on my screen.

**Comment by Bachibouzouk** [comment]
> > Maybe it is only for other years?
> 
> Maybe. I'll check. In any case i don't know if it's nice to leave them in, when they don't show anything in a realistic/normal setting.

@christian-rli  - you can choose that by commenting the lines you don't want to have in [here](https://github.com/rl-institut/WAM_APP_FRED/blob/354e3c3810f31bdd56e2665ee7d9755f2bdfe2af/forms.py#L5)

**Comment by christian-rli** [comment]
It's a bit sad not have wind in there, but now all variables work for me. If it's fine to disregard tests, I approve of the changes.

**Pull request merged**
