### PR TITLE
Add csv button to download the data

### PR DESCRIPTION
**Pull request by Bachibouzouk**
#111 has to be merged first

### CODE REVIEW

**Review by christian-rli — CHANGES_REQUESTED** [review]
There is a "to csv" link, but clicking on it does nothing. If I right click, I can save the page as html. Anything I should've done differently?

**Comment by Bachibouzouk** [comment]
> There is a "to csv" link, but clicking on it does nothing. If I right click, I can save the page as html. Anything I should've done differently?

Oh yes sorry, you need to 

`python manage.py makemigrations`

`python manage.py migrate`

because I use a model to save the data on the python side which needs to be initialized

(on the server these will be done automatically at the wam core level I presume)

**Comment by christian-rli** [comment]
The server does not like the most recent changes:
```
[2019-07-29 12:19:59 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:44)
[2019-07-29 14:19:59 +0200] [44] [INFO] Worker exiting (pid: 44)
There are  33014  powerplants in the data base
[2019-07-29 12:20:00 +0000] [57] [INFO] Booting worker with pid: 57
Internal Server Error: /WAM_APP_FRED/FeedinlibPopup.data/
Traceback (most recent call last):
  File "/opt/conda/envs/django/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "WAM_APP_FRED_csvrow" does not exist
LINE 1: DELETE FROM "WAM_APP_FRED_csvrow"
```

**Comment by christian-rli** [comment]
After migrations on the server it works :)

**Review by christian-rli — APPROVED** [review]
✓

**Pull request merged**
